title: Server Setup

author:
  name: IndexerDAO
  
# description: description would go here

github:
  is_project_page: true
  
# remote_theme: pages-themes/hacker@v0.2.0

plugins:
- jekyll-remote-theme

theme: minima

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/IndexerDAO" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UC-YZuNU8-50gjeV04yVb6gQ" }
    - { platform: github, user_url: "https://github.com/indexerdao" }

header_pages:
  - Guides.md
