# title: title would go here
# description: description would go here
github:
  is_project_page: true
  
# remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

theme: minima

minima:
  skin: auto
  date_format: "%b %-d, %Y"

header_pages:
  - Launchpad-Part1.md
