title: Server Setup

github:
  is_project_page: true

plugins:
- jekyll-remote-theme

theme: minima

twitter_username: IndexerDAO
github_username: IndexerDAO

header_pages:
  - guides.md
  - resources.md
