# title: Server Setup

github:
  is_project_page: true

plugins:
- jekyll-remote-theme

theme: just-the-docs

# twitter_username: IndexerDAO
# youtube_username: @IndexerDAO
# github_username: IndexerDAO

# header_pages:
#   - Guides.md
